### ISSUE TITLE
Problems setting up

### ISSUE THREAD

**Issue by anshumanv** [tofuness/Toshocat#15]
After running `npm install` I ran `npm start` but the app threw and error:

```anshuman@anshuman:~/Programming/GIT/Toshocat$ sudo npm start

> Toshocat@0.1.12 start /home/anshuman/Programming/GIT/Toshocat
> electron .

App threw an error during load
Error: Module version mismatch. Expected 50, got 57.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/anshuman/Programming/GIT/Toshocat/main/MediaDetector.js:3:17)
```

My environment is ubuntu 17, x86

**Comment by tofuness** [comment]
@anshumanv There are some native modules that makes the build only work on Windows (if I remember correctly). In other words, you need a Windows machine.

Currently working on a new updated Toshocat (private repo).

**Comment by anshumanv** [comment]
Okay then, I'll probably give it a try building it on windows arch.
Eager to see the updated Toshocat ! :smile: 
Since you're experienced with anime related apps, I build a little something here https://github.com/anshumanv/ongaku so needed scope for improvement, suggestions etc.
Closing this.
